# config/shakapacker.yml
default: &default
  source_path: app/javascript
  source_entry_path: packs
  nested_entries: true

  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  webpack_compile_output: true
  shakapacker_precompile: true

  additional_paths: []

  cache_manifest: false

  webpack_loader: 'babel'

  ensure_consistent_versioning: false

  compiler_strategy: digest
  useContentHash: false

development:
  <<: *default
  compile: true
  compiler_strategy: mtime

  dev_server:
    host: localhost
    port: 3035
    hmr: false
    inline_css: true
    compress: true
    allowed_hosts: 'auto'
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  useContentHash: true
  cache_manifest: true
entrypoints:
  home:
    source: 'app/javascript/components/Home.jsx'
    output: 'public/packs/js/home-bundle.js'